GET http://localhost:8080/api/u/
    ?page=1

###

GET http://localhost:8080/api/p/
    ?page=1

###

GET http://localhost:8080/api/p/621395bffbdde56add373289

###

GET http://localhost:8080/me
Authorization: bearer
GET http://localhost:8080/api/p/62142e9552769e357f790944

### userLiker / PostId du owner

POST  http://localhost:8080/api/p/62142d0952769e357f790940/621828fa5701d4673c63fd50

###

GET  http://localhost:8080/api/p/62140a9ddffb7fb444c4c539/like
Authorization: bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ilh2RmhJekN1UTljQjFDdW5yaGdDciJ9.eyJodHRwOi8vbG9jYWxob3N0Ly9lbWFpbCI6InRlc3RAZW1haWwuY29tIiwiaXNzIjoiaHR0cHM6Ly9iZWlrby51cy5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjIwNzcyMDU1OWNmNzcwMDZhNTU4ZDFiIiwiYXVkIjpbImh0dHBzOi8vYmVpa28udXMuYXV0aDAuY29tL2FwaS92Mi8iLCJodHRwczovL2JlaWtvLnVzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2NDYxODIzMTAsImV4cCI6MTY0NjI2ODcxMCwiYXpwIjoid2tUWU5ncWU3NDNiUnVjbGhGTXpJMVFrQWlOd2xReEciLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIn0.Q74fcpxnf6Wji0xNQIj4EH93dTyvyuDWQ2DVQhghnXV0KGVConxHec5F9hLOikMU_Ad-XXIyv_2xz3722MjWs0u-dSW0exr-wEPkLyX0C2sWNJ0OfBVBNgjKOqRo1knFSNXzSRMg-pFRuc9pncTWN6rKsz-3S6fLwdmlXUQBAYa4VHUh_AfRt_9_Cxev7q0jU3j32WQLslvuTQIiKOiaZ3VoTDWzsFCO1AjiefZGXTaHoDMWnIS2k7MBeCunArEmDfU_KNEFLpUtrZSpaD591dPo2ciPWbUvPcbPElafD-zJ570ByqBWzuN4tjReO8FNOlDKS21jrg7LSwt-xSLwYg

###

POST  http://localhost:8080/api/p/62140a9ddffb7fb444c4c539/like
Authorization: bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ilh2RmhJekN1UTljQjFDdW5yaGdDciJ9.eyJodHRwOi8vbG9jYWxob3N0Ly9lbWFpbCI6InRlc3RAZW1haWwuY29tIiwiaXNzIjoiaHR0cHM6Ly9iZWlrby51cy5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjIwNzcyMDU1OWNmNzcwMDZhNTU4ZDFiIiwiYXVkIjpbImh0dHBzOi8vYmVpa28udXMuYXV0aDAuY29tL2FwaS92Mi8iLCJodHRwczovL2JlaWtvLnVzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2NDYxODIzMTAsImV4cCI6MTY0NjI2ODcxMCwiYXpwIjoid2tUWU5ncWU3NDNiUnVjbGhGTXpJMVFrQWlOd2xReEciLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIn0.Q74fcpxnf6Wji0xNQIj4EH93dTyvyuDWQ2DVQhghnXV0KGVConxHec5F9hLOikMU_Ad-XXIyv_2xz3722MjWs0u-dSW0exr-wEPkLyX0C2sWNJ0OfBVBNgjKOqRo1knFSNXzSRMg-pFRuc9pncTWN6rKsz-3S6fLwdmlXUQBAYa4VHUh_AfRt_9_Cxev7q0jU3j32WQLslvuTQIiKOiaZ3VoTDWzsFCO1AjiefZGXTaHoDMWnIS2k7MBeCunArEmDfU_KNEFLpUtrZSpaD591dPo2ciPWbUvPcbPElafD-zJ570ByqBWzuN4tjReO8FNOlDKS21jrg7LSwt-xSLwYg

###

DELETE http://localhost:8080/api/p/62140a9ddffb7fb444c4c539/like
Authorization: bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ilh2RmhJekN1UTljQjFDdW5yaGdDciJ9.eyJodHRwOi8vbG9jYWxob3N0Ly9lbWFpbCI6InRlc3RAZW1haWwuY29tIiwiaXNzIjoiaHR0cHM6Ly9iZWlrby51cy5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjIwNzcyMDU1OWNmNzcwMDZhNTU4ZDFiIiwiYXVkIjpbImh0dHBzOi8vYmVpa28udXMuYXV0aDAuY29tL2FwaS92Mi8iLCJodHRwczovL2JlaWtvLnVzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2NDYxODIzMTAsImV4cCI6MTY0NjI2ODcxMCwiYXpwIjoid2tUWU5ncWU3NDNiUnVjbGhGTXpJMVFrQWlOd2xReEciLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIn0.Q74fcpxnf6Wji0xNQIj4EH93dTyvyuDWQ2DVQhghnXV0KGVConxHec5F9hLOikMU_Ad-XXIyv_2xz3722MjWs0u-dSW0exr-wEPkLyX0C2sWNJ0OfBVBNgjKOqRo1knFSNXzSRMg-pFRuc9pncTWN6rKsz-3S6fLwdmlXUQBAYa4VHUh_AfRt_9_Cxev7q0jU3j32WQLslvuTQIiKOiaZ3VoTDWzsFCO1AjiefZGXTaHoDMWnIS2k7MBeCunArEmDfU_KNEFLpUtrZSpaD591dPo2ciPWbUvPcbPElafD-zJ570ByqBWzuN4tjReO8FNOlDKS21jrg7LSwt-xSLwYg
